### ISSUE TITLE
shared_ptr error

### ISSUE THREAD

**Issue by adam-muk** [MIT-SPARK/Spark-DSG#1]
Hi. I am trying to build spark-dsg outside of a catkin environment. I am getting the following error but I have boost installed:
error: ‘shared_ptr’ in namespace ‘boost’ does not name a template type
  141 |   static BoundingBox extract(const boost::shared_ptr<const CloudT>& cloud,

Do you know why I would get this error?

**Comment by nathanhhughes** [comment]
Hi, thanks for your interest (and for filing the issue)!  I'm guessing you're on a system with a newer boost install. Can you try [this](https://github.com/MIT-SPARK/Spark-DSG/tree/fix/remove_boost_shared) branch instead? You should be able to just checkout the branch (i.e. `git checkout fix/remove_boost_shared`) and proceed as before to the pip install.  I've tried it locally on both a ubuntu 22.04 and ubuntu 18.04 machine, but just want final confirmation that there's nothing else going on before I merge #2.

**Comment by adam-muk** [comment]
Hi. Thanks for responding promptly. Spark-dsg built but gtest did not. I think it is an error with my PCL package?
![Screenshot from 2022-08-26 10-10-29](https://user-images.githubusercontent.com/5676480/186855431-db34c664-7bf0-4cc9-9861-c84658a815cf.png)

**Comment by nathanhhughes** [comment]
Sorry, should have read your first comment closer and realized you were building with cmake, not pip (which disables the unit tests by default). I was missing an include (`pcl/conversions.h`) that used to be including implicitly in older pcl versions. I merged #2, so hopefully `main` should be all set and you shouldn't run into any more build issues.  Feel free to close this issue if `main` does in fact build.

**Comment by adam-muk** [comment]
Great it builds now ;D
