### ISSUE TITLE
Error runing visualization with open3d_visualization.py and hydra

### ISSUE THREAD

**Issue by cassieqiuyd** [MIT-SPARK/Spark-DSG#20]
Hi, 

I am using this along with hydra and habitat-sim mp3d dataset, and encountered problems:

1. If I directly run hydra visualize, I would get Type error:
   

> File "/opt/conda/lib/python3.9/site-packages/spark_dsg/open3d_visualization.py", line 325, in _update_render_geometry
>     self._viz.update_geometry(name, geom, mat)
> TypeError: update_geometry(): incompatible function arguments. The following argument types are supported:
>     1. (self: open3d.cuda.pybind.visualization.O3DVisualizer, arg0: str, arg1: open3d.cuda.pybind.t.geometry.Geometry, arg2: int) -> None

and I looked at several documents with O3DVisualizer.update_geometry, which all required the same format. The problem seems to be that the input geom was open3d.cuda.pybind.geometry.Geometry, not the tensor, and from open3D document it also states that update_geometry only works with Pointcloud, not Lineset or mesh. Also mat is Material Record, not int. I am wondering which open3D version should be used to make it work, since I had tried from 0.14 to 0.18. Version 0.13 gives a segmentation fault though. 

2. I tried to change arg2 to int and arg1 to the tensor version, but with the pointcloud I got the follwing error:

> File "/opt/conda/lib/python3.9/site-packages/spark_dsg/open3d_visualization.py", line 324, in _update_render_geometry
>     self._viz.update_geometry(name, geom, o3d.visualization.rendering.Scene.UPDATE_POINTS_FLAG)
> IndexError: _Map_base::at

I am not sure where this error comes from.

3.  If I comment out the rendering part, the visualization still has some issues, like the same node of the object was kept to be added, and the room seems to have color codings wrong. 

 
![Screenshot from 2024-11-05 21-07-03](https://github.com/user-attachments/assets/19625288-5073-4f49-b412-f2eb822512c9)

I am also wondering if it is easier to generate the scene graph offline instead of online? or the generated scene graph already stored somewhere?

**Comment by nathanhhughes** [comment]
Thanks for your interest in our work! Unfortunately when we updated the open3d visualization to add text, we only tested by loading static scene graphs (and didn't realize that the open3d visualizer we switched to no longer supported updating geometries that had been added). I've reworked the visualizer to avoid the issue (and will be merging it into main momentarily), hopefully this resolves things on your end!
