### ISSUE TITLE
cloud you please provide uh2_office_dsg.json file

### ISSUE THREAD

**Issue by gaowutong** [MIT-SPARK/Spark-DSG#4]
Hello! 

I am pretty interesting about the project and am going to run the demo bindings_demo.py. However, I noticed that the file uh2_office_dsg.json is not included. Could you please provide this file so that it would be a good start for me to learn the project. 

Thank you very much!

**Comment by nathanhhughes** [comment]
Hi, thanks for your interest in our work! I unfortunately don't have a version of `uh2_office_dsg.json` that I'm sure is compatible with `main` for this version of Spark-DSG on hand (our internal version has changed slightly). It'll take me a little bit (a week or so) to have the time to regenerate it with the open-source version of Hydra. However, you can check out [Hydra](https://github.com/MIT-SPARK/Hydra) and generate it yourself in the meantime.  If you run the uhumans2 example (see [here](https://github.com/MIT-SPARK/Hydra#running-hydra-quickstart)), the json file should be saved under [this](https://github.com/MIT-SPARK/Hydra/tree/main/hydra_dsg_builder/output/uhumans2/office/backend) directory as `dsg.json`.
